on: 
  workflow_dispatch: #run manually
  push:
    paths:
      - .env

jobs:
  rocky_8_build_job:
    runs-on: ubuntu-latest
    name: A job to build rocky 8
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Load environment
        run: cp .env '%{{ github.env }}'
      - name: Set image name
        run: echo 'IMAGE_NAME=Rocky:8' >> '${{ github.env }}'
      - name: Build ${{ env.IMAGE_NAME }}
        working-directory: .github/actions/rocky-8-build
        run: docker build --build-arg --tag ${{ env.IMAGE_NAME }} --load .
      - name: docker login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push ${{ env.IMAGE_NAME }}
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ env.IMAGE_NAME }}
      - name: Rocky 8 build action step
        id: build
        uses: ./.github/actions/rocky-8-build
      # Use the output from the `hello` step
      - name: Build
        run: echo "The time was ${{ steps.hello.outputs.time }}"
